"""empty message

Revision ID: 65b9de530681
Revises: 
Create Date: 2018-04-27 00:30:23.202606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b9de530681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_call_start',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=11), nullable=False),
    sa.Column('destination', sa.String(length=11), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index(op.f('ix_phone_call_start_destination'), 'phone_call_start', ['destination'], unique=False)
    op.create_index(op.f('ix_phone_call_start_end_timestamp'), 'phone_call_start', ['end_timestamp'], unique=False)
    op.create_index(op.f('ix_phone_call_start_source'), 'phone_call_start', ['source'], unique=False)
    op.create_index(op.f('ix_phone_call_start_start_timestamp'), 'phone_call_start', ['start_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_call_start_timestamp'), table_name='phone_call_start')
    op.drop_index(op.f('ix_phone_call_start_source'), table_name='phone_call_start')
    op.drop_index(op.f('ix_phone_call_start_end_timestamp'), table_name='phone_call_start')
    op.drop_index(op.f('ix_phone_call_start_destination'), table_name='phone_call_start')
    op.drop_table('phone_call_start')
    # ### end Alembic commands ###
